#!/usr/bin/env python3
""" ups-mon  -  Displays current status of all active UPSs.

    A utility to give the current state of all compatible UPSs. The default
    behavior is to continuously update a text based table in the current window
    until Ctrl-C is pressed.  With the *--gui* option, a table of relevant
    parameters will be updated in a Gtk window.  You can specify the delay
    between updates with the *--sleep N* option where N is an integer > 10 that
    specifies the number of seconds to sleep between updates.  The *--log*
    option is used to write all monitor data to a psv log file.  When writing
    to a log file, the utility will indicate this in red at the top of the
    window with a message that includes the log file name.  The *--status*
    option will output a table of the current status.  The *--long* option will
    include additional informational parameters. By default, unresponsive UPSs
    will not be displayed, but the *--show_unresponsive* can be used to force
    their display.

    Copyright (C) 2019  RicksLab

    This program is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the Free
    Software Foundation, either version 3 of the License, or (at your option)
    any later version.

    This program is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
    more details.

    You should have received a copy of the GNU General Public License along with
    this program.  If not, see <https://www.gnu.org/licenses/>.
"""
__author__ = 'RicksLab'
__copyright__ = 'Copyright (C) 2019 RicksLab'
__license__ = 'GNU General Public License'
__program_name__ = 'ups-mon'
__maintainer__ = 'RicksLab'
__docformat__ = 'reStructuredText'
# pylint: disable=multiple-statements
# pylint: disable=line-too-long
# pylint: disable=bad-continuation

import argparse
import threading
import os
import sys
import re
import time
import logging
import pprint
from typing import TextIO, List, Any, Callable, Tuple, Union
try:
    import gi
    gi.require_version('Gtk', '3.0')
    from gi.repository import GLib, Gtk
except ModuleNotFoundError as error:
    print('gi import error: {}'.format(error))
    print('gi is required for %s', __program_name__)
    print('   In a venv, first install vext:  pip install --no-cache-dir vext')
    print('   Then install vext.gi:  pip install --no-cache-dir vext.gi')
    sys.exit(0)
from UPSmodules import UPSmodule as UPS
from UPSmodules import env
from UPSmodules import UPSgui
from UPSmodules import __version__, __status__, __credits__

set_gtk_prop = UPSgui.GuiProps.set_gtk_prop
LOGGER = logging.getLogger('ups-utils')
MAX_WIDTH = 23


class MonitorWindow(Gtk.Window):
    """
    Class defining Monitor Window
    """
    def __init__(self, ups_list: UPS.UpsList, devices: dict):
        """ Initialize the main UPS monitor window.

        :param ups_list:  The ups list object
        :param devices: A dictionary of Gtk components and values
        """
        self.quit: bool = False

        # RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
        Gtk.Window.__init__(self, title='{} - Monitor'.format(env.UT_CONST.gui_window_title))
        init_chk_value = Gtk.init_check(sys.argv)
        LOGGER.debug('init_check: %s', init_chk_value)
        if not init_chk_value[0]:
            print('Gtk Error, Exiting')
            sys.exit(-1)
        self.set_border_width(0)
        UPSgui.GuiProps.set_style()

        if env.UT_CONST.icon_file:
            LOGGER.debug('Icon file: [%s]', env.UT_CONST.icon_file)
            if os.path.isfile(env.UT_CONST.icon_file):
                self.set_icon_from_file(env.UT_CONST.icon_file)

        grid = Gtk.Grid()
        self.add(grid)
        gc = UPSgui.GuiComp(ups_list)

        col = 0
        row = 0
        num_ups_dict = ups_list.num_upss()
        num_ups = num_ups_dict['total'] if env.UT_CONST.show_unresponsive else num_ups_dict['responsive']

        # Set logging details at top of table if logging enabled
        if LOGGER.getEffectiveLevel() == logging.DEBUG:
            log_label = Gtk.Label(name='warn_label')
            log_label.set_markup('<big><b> DEBUG Logger Active </b></big>')
            lbox = Gtk.Box(spacing=6, name='warn_box')
            set_gtk_prop(log_label, top=1, bottom=1, right=1, left=1)
            lbox.pack_start(log_label, True, True, 0)
            grid.attach(lbox, 0, row, num_ups + 1, 1)
        row += 1
        if env.UT_CONST.LOG:
            log_label = Gtk.Label(name='warn_label')
            log_label.set_markup('<big><b> Logging to:    </b>' + env.UT_CONST.log_file + '</big>')
            lbox = Gtk.Box(spacing=6, name='warn_box')
            set_gtk_prop(log_label, top=1, bottom=1, right=1, left=1)
            lbox.pack_start(log_label, True, True, 0)
            grid.attach(lbox, 0, row, num_ups + 1, 1)
        row += 1
        row_start = row

        # Set first column of table to static values
        row = row_start
        row_labels = {'display_name': Gtk.Label(name='white_label')}
        row_labels['display_name'].set_markup('<b>UPS Parameters</b>')
        # Set row labels for header items
        for param_name, param_label in UPS.UpsItem._param_labels.items():
            if param_name not in UPS.UpsItem._table_list: continue
            row_labels[param_name] = Gtk.Label(name='white_label')
            row_labels[param_name].set_markup('<b>{}</b>'.format(param_label))
        # Set boxes for each row label
        for row_label_item in row_labels.values():
            lbox = Gtk.Box(spacing=6, name='head_box')
            set_gtk_prop(lbox, top=1, bottom=1, right=1, left=1)
            set_gtk_prop(row_label_item, top=1, bottom=1, right=4, left=4, align=(0.0, 0.5))
            lbox.pack_start(row_label_item, True, True, 0)
            grid.attach(lbox, col, row, 1, 1)
            row += 1

        #def_box_css = "{ background-image: image(%s); }" % UPSgui.GuiProps.color_name_to_hex('slate_md')
        # for item_name, item_ups in ups.get_ups_list(errups=env.UT_CONST.show_unresponsive).items():
        for ups in ups_list.upss():
            #gc.add(uuid, name, label, box)
            devices[ups.prm.uuid] = {'display_name':  Gtk.Label(name='white_label')}
            devices[ups.prm.uuid]['display_name'].set_markup('<b>CARD{}</b>'.format(ups['display_name']))
            devices[ups.prm.uuid]['display_name'].set_use_markup(True)
            for param_name in UPS.UpsItem._param_labels:
                if param_name not in UPS.UpsItem._table_list: continue
                devices[ups.prm.uuid][param_name] = Gtk.Label(label=ups[param_name], name='white_label')
                devices[ups.prm.uuid][param_name].set_width_chars(MAX_WIDTH)
                set_gtk_prop(devices[ups.prm.uuid][param_name], width_chars=MAX_WIDTH)

        for gui_component in devices.values():
            col += 1
            row = row_start
            for comp_name, comp_item in gui_component.items():
                comp_item.set_text('')
                if comp_name == 'display_name':
                    lbox = Gtk.Box(spacing=6, name='head_box')
                else:
                    lbox = Gtk.Box(spacing=6, name='med_box')
                set_gtk_prop(lbox, top=1, bottom=1, right=1, left=1)
                set_gtk_prop(comp_item, top=1, bottom=1, right=3, left=3, width_chars=MAX_WIDTH)
                lbox.pack_start(comp_item, True, True, 0)
                grid.attach(lbox, col, row, 1, 1)
                row += 1

        if LOGGER.getEffectiveLevel() == logging.DEBUG:
            log_message = ''
            for k, v in devices.items():
                if log_message: log_message = '{}\n\n{}:'.format(log_message, k)
                else: log_message = '{}:\n\n'.format(k)
                for k2, v2 in v.items():
                    log_message = '{}\n    {}:{}'.format(log_message, k2, v2)
            LOGGER.debug('Device dict:\n %s', log_message)

    def set_quit(self, _arg2: Any, _arg3: Any) -> None:
        """ Function called when quit monitor is executed.  Sets flag to end update loop.

        :param _arg2: Ignored
        :param _arg3: Ignored
        :return: None
        """
        self.quit = True


def update_data(ups_list: UPS.UpsList, devices: dict) -> None:
    """ Function that updates data in MonitorWindow  with call to read data from ups.

    :param ups_list:  The main ups module object
    :param devices: A dictionary of Gtk components and values
    :return: None
    """
    ups_list.read_all_ups_list_items(UPS.UpsComm.MIB_group.dynamic, errups=env.UT_CONST.show_unresponsive)
    if env.UT_CONST.LOG:
        print_log(env.UT_CONST.log_file_ptr, ups_list)

    # update gui
    for dev_uuid, dev_data in devices.items():
        ups = ups_list[dev_uuid]
        if not ups['valid']:
            state_style = UPSgui.Text_style.warn
            mib_name = 'mib_system_status'
            gui_comp = dev_data[mib_name]
            lv = gui_comp['label']
            box_name = gui_comp['box_name']
            lv.set_markup('<b>{}</b>'.format('Unresponsive'))
            UPSgui.GuiProps.set_style(css_str="#%s { background-image: image(%s); }" % (
                box_name, UPSgui.GuiProps.color_name_to_hex('yellow')))
            continue
        for mib_name, gui_comp in dev_data.items():
            state_style = UPSgui.Text_style.normal
            data_value = str(ups[mib_name])[:MAX_WIDTH]
            lv = gui_comp['label']
            box_name = gui_comp['box_name']
            if data_value == '-1':
                data_value = ''
            if mib_name == 'mib_battery_capacity' and data_value.isnumeric():
                if int(data_value) <= ups_list.daemon.daemon_params['threshold_battery_capacity']['crit']:
                    state_style = UPSgui.Text_style.crit
                elif int(data_value) <= ups.daemon.daemon_params['threshold_battery_capacity']['warn']:
                    state_style = UPSgui.Text_style.warn
            elif mib_name == 'mib_output_load' and data_value.isnumeric():
                if int(data_value) >= ups.daemon.daemon_params['threshold_battery_load']['crit']:
                    state_style = UPSgui.Text_style.crit
                elif int(data_value) >= ups.daemon.daemon_params['threshold_battery_load']['warn']:
                    state_style = UPSgui.Text_style.warn
            elif mib_name == 'mib_battery_status':
                if re.match(env.UT_CONST.PATTERNS['NORMAL'], data_value):
                    state_style = UPSgui.Text_style.green
                else:
                    state_style = UPSgui.Text_style.crit
            elif mib_name == 'mib_system_status':
                if re.match(env.UT_CONST.PATTERNS['ONLINE'], data_value):
                    state_style = UPSgui.Text_style.green
                else:
                    state_style = UPSgui.Text_style.crit
            elif mib_name == 'display_name':
                state_style = UPSgui.Text_style.bold

            set_gtk_prop(lv, width_chars=MAX_WIDTH+1)
            if state_style == UPSgui.Text_style.crit:
                lv.set_markup('<b>{}</b>'.format(data_value))
                UPSgui.GuiProps.set_style(css_str="#%s { background-image: image(%s); }" % (
                    box_name, UPSgui.GuiProps.color_name_to_hex('red')))
            elif state_style == UPSgui.Text_style.warn:
                lv.set_markup('<b>{}</b>'.format(data_value))
                UPSgui.GuiProps.set_style(css_str="#%s { background-image: image(%s); }" % (
                    box_name, UPSgui.GuiProps.color_name_to_hex('yellow')))
            elif state_style == UPSgui.Text_style.green:
                lv.set_markup('<b>{}</b>'.format(data_value))
                UPSgui.GuiProps.set_style(css_str="#%s { background-image: image(%s); }" % (
                    box_name, UPSgui.GuiProps.color_name_to_hex('green_dk')))
            elif state_style == UPSgui.Text_style.bold:
                lv.set_markup('<b>{}</b>'.format(data_value))
            else:
                lv.set_text(data_value)

    while Gtk.events_pending():
        Gtk.main_iteration_do(True)


def refresh(refresh_time: int, updater: Callable, ups_list: UPS.UpsList,
            devices: dict, umonitor: MonitorWindow) -> None:
    """ Function that continuously updates the Gtk monitor window.

    :param refresh_time:  Delay time in seconds between monitor display refreshes
    :param updater:  Function to update data
    :param ups_list:  UPS list object
    :param devices: A dictionary of Gtk components and values
    :param umonitor: The main Gtk monitor window.
    :return: None
    """
    while True:
        if umonitor.quit:
            print('Quitting...')
            Gtk.main_quit()
            sys.exit(0)
        GLib.idle_add(updater, ups_list, devices)
        for _sleep_cnt in range(0, refresh_time):
            if umonitor.quit:
                print('Quitting...')
                Gtk.main_quit()
                sys.exit(0)
            time.sleep(1)


def print_monitor_table(ups_list: UPS.UpsList) -> bool:
    """ Print the monitor table in format optimized for terminal window.

    :param ups_list:  The main ups module object
    :return: True on success
    """
    hrw = 29  # Row header item width
    irw = MAX_WIDTH + 1  # Row data item width

    print('┌', '─'.ljust(hrw, '─'), sep='', end='')
    for _ in ups_list:
        print('┬', '─'.ljust(irw, '─'), sep='', end='')
    print('┐')

    print('│', '\x1b[1;36m' + 'UPS Parameters'.ljust(hrw, ' ') + '\x1b[0m', sep='', end='')
    for ups in ups_list.upss():
        print('│', '\x1b[1;36m' + ups['display_name'].ljust(irw, ' ') + '\x1b[0m',
              sep='', end='')
    print('│')

    print('├', '─'.ljust(hrw, '─'), sep='', end='')
    for _ in ups_list:
        print('┼', '─'.ljust(irw, '─'), sep='', end='')
    print('┤')

    for table_item, item_name in UPS.UpsItem._param_labels.items():
        if table_item not in UPS.UpsItem._table_list: continue
        print('│{}{}{}'.format(env.UT_CONST.mark_up_codes['bcyan'],
              item_name.ljust(hrw, ' ')[:hrw], env.UT_CONST.mark_up_codes['reset']), sep='', end='')
        for ups in ups_list.upss():
            try:
                color = reset = 'none'
                if table_item == 'mib_system_status':
                    color = 'ok' if re.match(env.UT_CONST.PATTERNS['ONLINE'], ups[table_item]) else 'error'
                    reset = 'reset'
                elif table_item == 'mib_battery_status':
                    color = 'ok' if re.match(env.UT_CONST.PATTERNS['NORMAL'], ups[table_item]) else 'error'
                    reset = 'reset'
                value = '---' if ups[table_item] is None else str(ups[table_item])
                item_str = '{}{}{}'.format(env.UT_CONST.mark_up_codes[color],
                                           value.ljust(irw, ' ')[:irw],
                                           env.UT_CONST.mark_up_codes[reset])
            except KeyError:
                item_str = ' '.ljust(irw, ' ')[:irw]
            print('│', item_str, sep='', end='')
        print('│')

    print('└', '─'.ljust(hrw, '─'), sep='', end='')
    for _ in ups_list:
        print('┴', '─'.ljust(irw, '─'), sep='', end='')
    print('┘')
    return True


def print_log(fileptr: TextIO, ups_list: UPS.UpsList) -> None:
    """ Print the logfile data line.

    :param fileptr:  The logfile fileptr
    :param ups_list: A UPS list structure
    :return: None
    """
    time_str = (str(env.UT_CONST.now(ltz=True).strftime('%c')).strip())
    for ups in ups_list.upss():
        print('{}'.format(time_str), file=fileptr, end='')
        for table_item, item_name in UPS.UpsItem._param_labels.items():
            if table_item not in UPS.UpsItem._table_list: continue
            print('|{}'.format(ups[table_item]), file=fileptr, end='')
        print('', file=fileptr)


def print_log_header(fileptr: TextIO, ups_list: UPS.UpsList) -> None:
    """ Print the logfile header line.

    :param fileptr:  The logfile fileptr
    :param ups_list: A UPS list structure
    :return: None
    """
    print('time', file=fileptr, end='')
    for table_item, item_name in UPS.UpsItem._param_labels.items():
        if table_item not in UPS.UpsItem._table_list: continue
        print('|{}'.format(table_item), file=fileptr, end='')
    print('', file=fileptr)


def main() -> None:
    """
    Main function

    :return: None
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--about', help='README', action='store_true', default=False)
    parser.add_argument('--status', help='Display table of current status of UPSs', action='store_true', default=False)
    parser.add_argument('--long', help='Include static items', action='store_true', default=False)
    parser.add_argument('--show_unresponsive', help='Display unresponsive UPSs', action='store_true', default=False)
    parser.add_argument('--gui', help='Display GTK Version of Monitor', action='store_true', default=False)
    parser.add_argument('--log', help='Write all monitor data to logfile', action='store_true', default=False)
    parser.add_argument('--sleep', help='Number of seconds to sleep between updates',
                        type=int, default=UPS.UpsDaemon.daemon_param_defaults['read_interval']['monitor'])
    parser.add_argument('-d', '--debug', help='Debug output', action='store_true', default=False)
    args = parser.parse_args()

    # About me
    if args.about:
        print(__doc__)
        print('Author: ', __author__)
        print('Copyright: ', __copyright__)
        print('Credits: ', *['\n      {}'.format(item) for item in __credits__])
        print('License: ', __license__)
        print('Version: ', __version__)
        print('Install Type: ', env.UT_CONST.install_type)
        print('Maintainer: ', __maintainer__)
        print('Status: ', __status__)
        sys.exit(0)

    env.UT_CONST.set_env_args(args, __program_name__)
    LOGGER.debug('########## %s %s', __program_name__, __version__)

    if not env.UT_CONST.check_env():
        env.UT_CONST.log_print('Error in environment. Exiting...')
        sys.exit(-1)

    print('Reading and verifying UPSs listed in {}. '.format(env.UT_CONST.ups_json_file))
    ups_list = UPS.UpsList()
    num_ups = ups_list.num_upss()

    if not num_ups['total']:
        env.UT_CONST.log_print('No UPSs specified in {}'.format(env.UT_CONST.ups_json_file))
        print('    For more information: `man {0}`, exiting...'.format(env.UT_CONST.ups_json_file))
        sys.exit(-1)
    print('{} UPSs listed in {}.'.format(num_ups['total'], env.UT_CONST.ups_json_file))
    print('    {} are compatible, {} are accessible, {} are responsive, and {} are valid\n'.format(
        num_ups['compatible'], num_ups['accessible'], num_ups['responsive'], num_ups['valid']))
    if num_ups['total'] != num_ups['responsive']:
        print('    Check the {} file.\n'.format(env.UT_CONST.ups_json_file))

    if int(args.sleep) >= ups_list.daemon.daemon_param_defaults['read_interval']['limit']:
        env.UT_CONST.SLEEP = int(args.sleep)
    else:
        env.UT_CONST.log_print('Invalid value for sleep specified.  Must be an integer >= {}'.format(
            ups_list.daemon.daemon_param_defaults['read_interval']['limit']))
        env.UT_CONST.fatal = True

    if env.UT_CONST.fatal:
        env.UT_CONST.log_print('Fatal Error. Exiting...')
        sys.exit(-1)

    ups_list.read_all_ups_list_items(UPS.UpsComm.MIB_group.all, errups=args.show_unresponsive, display=False)

    env.UT_CONST.show_unresponsive = args.show_unresponsive

    if args.log:
        env.UT_CONST.LOG = True
        env.UT_CONST.log_file = './log_monitor_{}.txt'.format(
            env.UT_CONST.now(ltz=env.UT_CONST.USELTZ).strftime('%m%d_%H%M%S'))
        env.UT_CONST.log_file_ptr = open(env.UT_CONST.log_file, 'w', 1)
        print_log_header(env.UT_CONST.log_file_ptr, ups_list)

    if args.gui:
        # Display Gtk style Monitor
        devices = {}
        umonitor = MonitorWindow(ups_list, devices)
        umonitor.connect('delete-event', umonitor.set_quit)
        umonitor.show_all()

        # Start thread to update Monitor

        _monthread = threading.Thread(target=refresh, daemon=True, args=[env.UT_CONST.SLEEP,
                                      update_data, ups_list, devices, umonitor]).start()

        Gtk.main()
    else:
        # Display text style Monitor
        try:
            while True:
                ups_list.read_all_ups_list_items(UPS.UpsComm.MIB_group.monitor, errups=args.show_unresponsive, display=False)
                if args.status:
                    print_monitor_table(ups_list)
                    sys.exit(0)
                os.system('clear')
                if LOGGER.getEffectiveLevel() == logging.DEBUG:
                    print('%sDebug Logger Active%s' % ('\033[31m \033[01m', '\033[0m'))
                if env.UT_CONST.LOG:
                    print('%sLogging to:  %s%s' % ('\033[31m \033[01m', env.UT_CONST.log_file, '\033[0m'))
                    print_log(env.UT_CONST.log_file_ptr, ups_list)
                print_monitor_table(ups_list)
                time.sleep(env.UT_CONST.SLEEP)
        except KeyboardInterrupt:
            if env.UT_CONST.LOG:
                env.UT_CONST.log_file_ptr.close()
            sys.exit(0)


if __name__ == '__main__':
    main()
